"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import UI
import scraper

# Implementing MyFrame1
class MyProject1MyFrame1( UI.MyFrame1 ):
	def __init__( self, parent ):
		UI.MyFrame1.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def OnButtonRun( self, event ):
		text = self.m_textCtrl1.GetValue()
		if scraper.Scraper.scraper(text):
			self.m_textCtrl1.Clear()
		pass


