"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import MyClass

# Implementing MyFrame1
class MyProject1MyFrame1( MyClass.MyFrame1 ):
	def __init__( self, parent ):
		MyClass.MyFrame1.__init__( self, parent )

	def event1( self, event ):
		self.m_button1.SetLabel('clicked')
		pass